name: Build (for all supported platform)

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: settings.xml
      run: cat ~/.m2/settings.xml
    - name: Set up SWIG
      run: sudo apt-get install swig
    - name: Build with Maven
      run: mvn -B deploy --file pom.xml -Prelease -Pgithub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
